# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rgt', models.IntegerField()),
                ('lft', models.IntegerField()),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='channels.Channel')),
            ],
        ),
    ]
