# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='lft',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='rgt',
            field=models.IntegerField(default=1),
        ),
    ]
