# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20170714_2254'),
        ('channels', '0002_auto_20170713_1949'),
    ]

    operations = [
    ]
